kind: pipeline
name: common
steps:
  - name: environment check
    image: node:8
    commands:
      - npm --version
      - node --version
      - yarn --version
  - name: test application
    image: node:8
    commands:
      - npm install
      - npm test
  - name: run application
    image: node:8
    commands:
      - npm install
      - npm start