kind: pipeline
name: common
steps:
  - name: init echo
    image: node:8
    commands:
      - echo hello world
  - name: test application
    image: node:8
    commands:
      - npm test
  - name: run application
    image: node:8
    commands:
      - npm start