kind: pipeline
name: common
steps:
  - name: test yml
    image: alpine
    commands:
      - echo hello world
  - name: test
    image: alpine
    commands:
      - npm test
  - name: run
    image: alpine
    commands:
      - npm start